### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by StoneyJackson** [ourPLCC/course#1]
@ourPLCC/core,

## What?

* Repository `plcc` now contains PLCC, the tool.
* Repository `course` now contains the course materials for teaching programming languages using PLCC.

## Why?

* Separation of responsibilities
  - `plcc` is responsible for its design, implementation, testing, documentation, deployment, and use. In short, it's a software project.
  - `course` is responsible for the pedagogical approach to teaching programming languages and the course materials for doing so.
* Clarify dependencies: `course` depends on `plcc`.
* Reduce duplication: there is now one code-based for PLCC (the tool), `plcc` (the repository).

## How do I make changes?

Give me a chance to write a little guide on this.

## Feedback

Let me know if you disagree or have a better idea. I'm just doing what I think is right. But I'm open to critique and feedback.

**Comment by fosler** [comment]
AGREE! Thank you!

**Comment by jashelio** [comment]
Stoney,

Great organization.

I would like your advice.

From the beginning, I did not use Tim's notes. For my style, they were a bit too dense. (Since they were in LaTeX, I tried converting the source to more of a handbook format, but suspended that work due to lack of time.) So this last spring I finally made my own slides, using PowerPoint. Do you have any objection to my making another directory under course for that material? I'll alert Tim about it, but I think he already knows because we share ideas freely.

Also, we should put up the original LaTeX for Tim's slides, don't you think?

Thanks,
Jim

**Comment by jashelio** [comment]
> On May 16, 2020, at 12:52 PM, James Heliotis <jimelihel@icloud.com> wrote:
> 
> I'll alert Tim about it, but ...

Actually I don't know about these GitHub replies. Do they automatically go to every member of the group anyway?

Jim

**Comment by fosler** [comment]
All,

I agree that the LaTeX sources should also be provided (the entire JNotes directory?), and Jim's PowerPoint slides as well. Stoney, feel free to put together some sort of organization that would support this.

Jim, I looked at your PDF file that seems to be all my slides streamed together -- about 230 pages. It's a BOOK. Do you want to include that as well in the 'courses' part of ourPLCC? It should have some sort of copyright included, if it's not already there.

I made a couple of tweaks to the contents of the ABC language (essentially abcdatalog, wrapped in a PLCC front end) that gives solutions to the 'fox/goose/corn' river crossing problem and the 'missionaries and cannibals'. They are in the Code/ABC/Misc directory on pithon.net.

**Comment by StoneyJackson** [comment]
Awesome! When you reply using email, your reply is posted to the issue. Everyone who is involved in the issue gets a notification. You can customize how and when GitHub notifies you (see <https://help.github.com/en/github/managing-subscriptions-and-notifications-on-github/about-notifications>).

@fosler I think the LaTeX source would be a good addition. Could you put it in JNotes/src ? I can reorganize from there.

@jashelio I would love to get your slides in the repository as an alternative. How about adding them in a sub-directory of PowerPoint/

I've added a CONTRIBUTING.md file that explains how to contribute such changes. Let me know if you encounter bugs, or if you need any help.

**Comment by jashelio** [comment]
On May 16, 2020, at 13:55, fosler <notifications@github.com> wrote:
> 
> 
> Jim, I looked at your PDF file that seems to be all my slides streamed together -- about 230 pages. It's a BOOK. Do you want to include that as well in the 'courses' part of ourPLCC? It should have some sort of copyright included, if it's not already there.

No, please. That did not work out. Or at least it needs more work before I really make it public. I have not used it in a year. Its main problem is that it is missing the diagrams. And of course, if it's ever finished I will put Tim's copyright in there.

> I made a couple of tweaks to the contents of the ABC language (essentially abcdatalog, wrapped in a PLCC front end) that gives solutions to the 'fox/goose/corn' river crossing problem and the 'missionaries and cannibals'. They are in the Code/ABC/Misc directory on pithon.net.

Thanks. I never succeeded in getting that to work. It was not clear what I had to download from the abcdatalog folks to get it to work.

Jim

**Comment by jashelio** [comment]
Stony,

I have cloned the course and added PowerPoint/ but cannot push without review. So I await instructions.


Also I was not sure how to interpret this statement.
"There is now one code-based for PLCC (the tool), plcc (the repository)."
unless you're saying that the repository "plcc" is the code base for the PLCC tool.

The Git Newbie,
Jim

**Comment by fosler** [comment]
Oops, I forgot to include the abcdatalog.jar file in the ABC language directory. I have put the abcdatalog.jar file in the ABC language directory on pithon.net. I also revised the README.txt file in the ABC directory by giving instructions to copy this jar file into the Java directory and to set the CLASSPATH so compilation and runtime execution will work. I also renamed the 'Misc' directory to 'River' (for river crossing). Stoney, can you copy the abcdatalog.jar and README.txt files into the Code/ABC directory and change the name of 'Misc' to 'River'? Thanks!

--Tim

On 5/16/20 11:11 PM, James Heliotis wrote:
...
>  > I made a couple of tweaks to the contents of the ABC language (essentially abcdatalog, wrapped in a PLCC front end) that gives solutions to the 'fox/goose/corn' river crossing problem and the 'missionaries and cannibals'. They are in the Code/ABC/Misc directory on pithon.net.
> 
> Thanks. I never succeeded in getting that to work. It was not clear what I had to download from the abcdatalog folks to get it to work.
> 
> Jim
...

**Comment by fosler** [comment]
Correction: remove the phrase "to copy this jar file into the Java directory and". Thanks.

**Comment by StoneyJackson** [comment]
@jashelio  I don't see a pull-request on either project to review. Assuming you are following [these directions](https://github.com/ourPLCC/course/blob/master/CONTRIBUTING.md), on which step did it fail? And can you give me the output?

**Comment by StoneyJackson** [comment]
@fosler It's going to be difficult to maintain two copies of the project (pithon.net and this project). If you want to maintain pithon.net, it would be a lot easier to keep the two in synch if you make changes to this project, and then use Git to pull the source to your website (or wget or curl to pull zip files). This could even be automated using cron. I would be happy to help you learn how to make changes using Git and GitHub.

**Comment by StoneyJackson** [comment]
@jashelio @fosler Should we meet and go over how to contribute? Let me know the date of the first week you'll have some time, and I'll create a when2meet poll so we can find a time when we can meet.

This is getting exciting!

**Comment by jashelio** [comment]
Thanks, Stoney, and I found your instructions. I can follow them but I have to admit I still don't have a good mental model of Git use at this level. I'm not asking you to do it for me, however.

This diagram represents my level of understanding at the moment: https://www.cs.rit.edu/~csci142/Resources/JetBrains+GIT/ <https://www.cs.rit.edu/~csci142/Resources/JetBrains+GIT/>
(although I also know how to do all this from the command line.)

Right now I have to focus on my summer course. I'll readdress this at the end of June.

I really appreciate this project. It is forcing me to get comfortable with Git beyond the level at which I was using it!

Jim

**Comment by StoneyJackson** [comment]
OK, I think I've managed to untangle all the threads of discussion in this issue and have created separated issues for each topic. Now I'll start working through them.

Closing this issue.
