### ISSUE TITLE
Create a separate repository and issue tracker for meetings

### ISSUE THREAD

**Issue by StoneyJackson** [ourPLCC/course#10]
## Rationale

Using a separate repository with its own issue tracker will allow us to manage meetings, agenda items, minutes, etc., without muddying up the issue tracker for each project. It will also make it easier to find information about upcoming meetings and minutes from past meetings.

## Plan

1. Create a repository named ourPLCC/meetings
2. Move https://github.com/ourPLCC/course/issues/5 into the tracker of the new project.
3. Start using the new repository for future meetings.

## Change management

Making this change is low risk as all of the operations are non-destructive, reversible, and should not break anything we have now.

So I think I can reasonably make this change without explicit approval. I will be responsible for reverting the change if someone later objects.

**Comment by jashelio** [comment]
Sounds good.

**Comment by fosler** [comment]
Agreed!
