### ISSUE TITLE
Determine Workflow

### ISSUE THREAD

**Issue by StoneyJackson** [ourPLCC/course#5]
## Time and Place

Date: Tuesday, July 28, 2020
Time: 10-11:30 AM
Zoom: https://wne-edu.zoom.us/j/94686371529?pwd=ZndicXdqaldzeTBkZ3NoRjJoVCtuUT09

## Agenda

Originally, I was thinking we should meet for a training on Git and GitHub. But then I thought maybe it would be better to take a step back and make sure that we are in agreement on how we want to operate. I don't want to force anyone into something that isn't going to work well for them. So, here is an initial agenda I propose. 

- How do we want to coordinate and communicate?
- How do we want to manage changes?
    - What tools do we want to use?
    - What process/workflow do we want to use?
- Are any trainings necessary? When and how will we do them?
- Plugin for JetBrains

---

Please suggest changes or start the discussion by commenting on this issue.

**Comment by StoneyJackson** [comment]
@jashelio @fosler Summer is rapidly passing. I thought we should set up a time to meet and coordinate.

## Where

On Zoom. I'll create and post a link here when we know the date and time of the meeting.

## When to meet

I'm camping this week and next, so I thought we should consider dates in the last week of July or the first week of August. I've created a when2meet poll to help use pick a good time. Please use it to indicate the times your are available to meet. All times are in EST. And please remember this link (as is this issue) is public.

https://www.when2meet.com/?9370926-bA6AS 

If your availabilities change, when2meet will let you update them.

I'll try to pick a date/time that works well for everyone on Friday 7/24/2020. So please update your availabilities before that date.

## Meeting duration

We should probably block out a 1.5 hour block. We can always end the meeting earlier if we want to. Let me know if you think it should be longer or shorter.

## Agenda

Originally, I was thinking we should meet for a training on Git and GitHub. But then I thought maybe it would be better to take a step back and make sure that we are in agreement on how we want to operate. I don't want to force anyone into something that isn't going to work well for them. So, here is an initial agenda I propose. ***Please feel free to suggest additions, deletions, or changes.***

- How do we want to coordinate and communicate?
- How do we want to manage changes?
    - What tools do we want to use?
    - What process/workflow do we want to use?
- Are any trainings necessary? When and how will we do them?
- Plugin for JetBrains

**Comment by StoneyJackson** [comment]
@fosler @jashelio Thanks for marking your availabilities so quickly. In that case, let's going ahead and schedule the meeting for

- Tuesday, July 28, 2020 from 10a-11:30a EST.

I'll update the description of this issue with this information and a Zoom meeting link.

Until then feel free to leave comments on this issue suggesting changes to the proposed agenda and or start the discussion on one or more of the items.

I look forward to meeting you @jashelio and seeing you again @fosler!

**Comment by StoneyJackson** [comment]
Hi @ourPLCC/core,

This is a quick reminder that we have a meeting tomorrow at 10a. The details including a zoom link are at the top of this issue. Please take a look at the agenda on this issue and feel free to add or suggest changes for the agenda.

Can't wait to see you all on zoom! 👍

**Comment by jashelio** [comment]
If this mail note is in our GitHub repository, I can't find it. Remember, I'm a rookie at this.

But this is what I wrote down on my calendar:

https://wne-edu.zoom.us/j/94686371529?pwd=ZndicXdqaldzeTBkZ3NoRjJoVCtuUT09 <https://wne-edu.zoom.us/j/94686371529?pwd=ZndicXdqaldzeTBkZ3NoRjJoVCtuUT09>

Jim

**Comment by StoneyJackson** [comment]
@jashelio There should be a link back to the issue at the bottom of every email Notification from GitHub. Look for “view it on GitHub”.

That link looks correct. And our time is from 10-11:30a EST.

**Comment by StoneyJackson** [comment]
@ourPLCC/core I've created a temporary [Google Doc](https://docs.google.com/document/d/1osIWE0hV900iY94i2YXhWuVrMiu1yCVeQKXewHde8qw/edit?usp=sharing) so we can collaboratively record minutes. When the meeting is over, I'll make it read-only and copy its contents into this issue for the record.

Please remember this issue and the contents of that document are publicly visible.

**Comment by StoneyJackson** [comment]
@ourPLCC/core test

**Comment by StoneyJackson** [comment]
# Meeting - @ourPLCC/core - 2020-07-28

Issue: [https://github.com/ourPLCC/course/issues/5](https://github.com/ourPLCC/course/issues/5)

Date: Tuesday, July 28, 2020

Time: 10-11:30 AM

Zoom: [https://wne-edu.zoom.us/j/94686371529?pwd=ZndicXdqaldzeTBkZ3NoRjJoVCtuUT09](https://wne-edu.zoom.us/j/94686371529?pwd=ZndicXdqaldzeTBkZ3NoRjJoVCtuUT09)

This is a temporary document for collaboratively recording our meeting minutes. This document is **_publicly readable and writable_** during the meeting. After the meeting, the contents of the document will be copied to the issue linked above, which is **_publicly readable_**, and will remain there until the issue is deleted (if ever). This document will become read-only and will be deleted.


# Minutes

Meeting started at Tuesday, July 28, 2020 10a EST

Attending: Jim, Tim, Stoney

---

How do we want to coordinate and communicate?


*  Issues/Email
*  Zoom - regular meetings, bi-weekly
    *   August 11 @ 10a
    *   We'll schedule regular session at that time

----

How do we want to manage changes?



*   What tools do we want to use?
*   What process/workflow do we want to use?

Automated tests

Freeze for semester for our classes

Roadmap

- Possibly rewrite in Java
- Bug fixes
- ...

Collect issues from students for later implementation.	

PLCC - Communal and synchronized.

Course - Diverges - Might need some rearranging.

Other multiple projects in the future

----

Are any trainings necessary? When and how will we do them?

cede

----

Evangelize PLCC



*   Paper?
*   Logic Programming (course issue; but makes it more attractive to other instructors)

----

Java Annotation "PLCC" version



*   Prefer to keep semantics and syntax separate 

----

Plugin for JetBrains



*   Next meeting
*   Hopefully Mark Nash can attend.

Meeting adjourned at Tuesday, July 28, 2020 11:30a EST

**Comment by StoneyJackson** [comment]
Closing this issue as the meeting is done.
